# SwiftLint configuration file

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - trailing_whitespace
  - vertical_whitespace
  - operator_usage_whitespace
  - redundant_optional_initialization
  - unused_import
  - unused_private_declaration
  - unused_closure_parameter
  - closure_end_indentation
  - multiline_parameters
  - multiline_arguments

# Disabled rules
disabled_rules:
  - line_length
  - identifier_name

# Included paths
included:
  - ThirdFloor

# Excluded paths
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData

# File length
file_length:
  warning: 500
  error: 1000

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting
nesting:
  type_level: 2
  statement_level: 5

# Reporter
reporter: "xcode"
